eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  file:
    name: /home/manhtien/springboot-microservice-hotel-management/elk-stack.log
